//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jornal
{
    using System;
    using System.Collections.Generic;
    
    public partial class mark
    {
        public int id_m { get; set; }
        public int id_st { get; set; }
        public int id_pred { get; set; }
        public int mark1 { get; set; }
        public System.DateTime date_m { get; set; }
    }
}
