//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jornal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Jornal_DBEntities : DbContext
    {
        public Jornal_DBEntities()
            : base("name=Jornal_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<lesson> lessons { get; set; }
        public virtual DbSet<mark> marks { get; set; }
        public virtual DbSet<prava> pravas { get; set; }
        public virtual DbSet<predmet> predmets { get; set; }
        public virtual DbSet<t_st_pred> t_st_pred { get; set; }
        public virtual DbSet<teach_predmet> teach_predmet { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
