//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jornal
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_st_pred
    {
        public int id_tsp { get; set; }
        public int id_pred { get; set; }
        public int id_tch { get; set; }
        public int id_st { get; set; }
    }
}
