//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jornal
{
    using System;
    using System.Collections.Generic;
    
    public partial class teach_predmet
    {
        public int id_t_pr { get; set; }
        public int id_teach { get; set; }
        public int id_predmet { get; set; }
    }
}
